development: &default
  adapter: postgresql
  database: demo_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: <%= ENV['DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['DB_1_PORT_5432_TCP_PORT'] %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
